import OnboardingWrapper from '@/components/onboarding/onboarding-wrapper';
import Sidebar from '@/components/sidebar';
import { Dialog, DialogContent } from '@/components/ui/dialog';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <OnboardingWrapper>
          <div className="flex">
            <Sidebar />
            {children}
          </div>
        </OnboardingWrapper>
      </body>
    </html>
  );
}
